-- LOADPOST-2: Full cargo catalog seed from comprehensive master list
BEGIN;

INSERT INTO public.material_groups (code, name_en, sort_order)
VALUES
  ('minerals_ores', 'Minerals & Ores', 10),
  ('iron_steel', 'Iron & Steel', 20),
  ('chemicals', 'Chemicals', 30),
  ('plastic_rubber', 'Plastic & Rubber', 40),
  ('construction', 'Construction', 50),
  ('agri_products', 'Agri Products', 60),
  ('others', 'Others', 999)
ON CONFLICT (code) DO UPDATE
SET
  name_en = EXCLUDED.name_en,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();

WITH raw(name_en) AS (
  VALUES
    ('20 Feet Container'),
    ('40 Feet Container'),
    ('40HC Container'),
    ('AAC Blocks'),
    ('Acetic Acid'),
    ('Acetic Anhydride'),
    ('Acetic Ether'),
    ('Acetone'),
    ('Acetyl Chloride'),
    ('Acetylene'),
    ('Acid Carbolic'),
    ('Acid Chlorosulphonic'),
    ('Acid Chromic (Liquid)'),
    ('Acid Chromic (Solid)'),
    ('Acid Cresylic'),
    ('Acid Formic'),
    ('Acid Hydrobromic'),
    ('Acid Hydrochloric'),
    ('Acid Hydrofluoric'),
    ('Acid (Liquid)'),
    ('Acid Oxalic'),
    ('Acid Perchloric'),
    ('Acid Resisting Cement'),
    ('Agarbatti (Incense Sticks)'),
    ('Aggregate / Stone Chips'),
    ('Agricultural Implements'),
    ('Air Compressed'),
    ('Air Freight Cargo'),
    ('Ajwain (Carom Seeds)'),
    ('Alloy Constructional Steels'),
    ('Alloy Pipes'),
    ('Alloy Steel'),
    ('Alloy Steel Castings'),
    ('Alum'),
    ('Alumina'),
    ('Aluminium Billets'),
    ('Aluminium Extrusion'),
    ('Aluminium Foil'),
    ('Aluminium Ingot'),
    ('Aluminium Scrap'),
    ('Aluminium Sheets'),
    ('Aluminium Wire'),
    ('Alunite'),
    ('Ammonal'),
    ('Ammonia'),
    ('Ammonia (Anhydrous Liquefied Gas)'),
    ('Ammonia Liquefied Gas'),
    ('Ammonium Bicarbonate Food Grade'),
    ('Anhydrous Denatured Ethanol'),
    ('Animal Feed'),
    ('Anthracite Coal'),
    ('Apples'),
    ('Arecanut / Betel Nut'),
    ('Asbestos'),
    ('Asbestos Jointing and Packing Sheets'),
    ('Asbestos Sheets'),
    ('Ash'),
    ('Ashes'),
    ('ATF (Aviation Turbine Fuel)'),
    ('Auto Parts'),
    ('Automobiles (Cars / Bikes)'),
    ('Axles Iron or Steel NOC'),
    ('Axles with Wheels'),
    ('Ayurvedic Medicines'),
    ('Bajra'),
    ('Bajra (Pearl Millet)'),
    ('Bales (Cotton)'),
    ('Bales (Jute)'),
    ('Ballast'),
    ('Ballast Chips'),
    ('Bamboo'),
    ('Bananas'),
    ('Barbed Wire'),
    ('Barium'),
    ('Barium Carbonate'),
    ('Barium Chloride'),
    ('Barium Dioxide'),
    ('Barium Hydrate'),
    ('Barium Hydroxide'),
    ('Barium Peroxide'),
    ('Barium Sulphide'),
    ('Barium Superoxide'),
    ('Barley'),
    ('Barytes'),
    ('Barytes Powder'),
    ('Basic Lead Sulphate'),
    ('Basmati Rice'),
    ('Batteries (Auto / Inverter)'),
    ('Battery Charging Solution (Acid)'),
    ('Battery Charging Solution (Alkali)'),
    ('Battery Charging Solution (Lithium Solution)'),
    ('Battery Charging Solution (Potash)'),
    ('Bauxite'),
    ('Beams'),
    ('Beams (Prestressed Cement Concrete)'),
    ('Bed Ash'),
    ('Bengal Lights'),
    ('Bentonite'),
    ('Bentonite Powder'),
    ('Benzene'),
    ('Besan (Gram Flour)'),
    ('Bichloride of Mercury'),
    ('Bicycles'),
    ('Billets'),
    ('Billets (Steel)'),
    ('Biscuits'),
    ('Bitumen'),
    ('Bitumen Emulsion'),
    ('Black Pepper'),
    ('Bleaching Powder'),
    ('Bloom'),
    ('Blue Dust'),
    ('Boilers'),
    ('Books / Exercise Books / Note Books / Work Books'),
    ('Books & Magazines'),
    ('Boulders'),
    ('Brass Extrusion'),
    ('Brass Ingots'),
    ('Brass Scrap'),
    ('Breakbulk Cargo'),
    ('Breeze Coke'),
    ('Bricks Broken'),
    ('Bricks (Fly Ash)'),
    ('Bricks (Red)'),
    ('Briquetted Fuel Mixture'),
    ('Briquettes (Biomass)'),
    ('Bulk Bagged Cargo'),
    ('Bulk Cargo'),
    ('Bulk Cement'),
    ('Bulk Dry Cargo'),
    ('Bulk Liquid Cargo'),
    ('Burnt Lime'),
    ('Buses'),
    ('Butter / Ghee'),
    ('Cabbage'),
    ('Cables / Cable Drums'),
    ('Cake (Oil Cake)'),
    ('Calcined Petroleum Coke'),
    ('Calcium'),
    ('Calcium Carbonate'),
    ('Calibrated Lump Iron Ore'),
    ('Carbon Black'),
    ('Carbon Black Feed Stock'),
    ('Carbonic Acid Gas'),
    ('Carbonic Acid Gas (Compressed)'),
    ('Carbonic Acid (Liquefied)'),
    ('Carbonic Disulphide'),
    ('Card Boards'),
    ('Cardamom'),
    ('Carrots'),
    ('Cartons (Empty)'),
    ('Cashew'),
    ('Cast Iron Pipes'),
    ('Castor Oil'),
    ('Castor Seed'),
    ('Cattle Feed'),
    ('Cauliflower'),
    ('Caustic Soda'),
    ('Cement (Bags)'),
    ('Cement Blocks'),
    ('Cement (Bulker)'),
    ('Cement Pipes'),
    ('Cement Plaster'),
    ('Cement Sheets'),
    ('Cement Tiles'),
    ('Cement (White)'),
    ('Ceramic Tiles'),
    ('Chalk'),
    ('Chalk Calcium Carbonate'),
    ('Chalk in Lumps or Powder'),
    ('Chana (Bengal Gram)'),
    ('Chana Dal'),
    ('Channels'),
    ('Charcoal'),
    ('Charge / Parcel'),
    ('Chassis (Truck / Bus)'),
    ('Cheese'),
    ('Chemical Gypsum'),
    ('Chemicals (Dry / Bags)'),
    ('Chemicals (Liquid / Barrels)'),
    ('Chillies (Dry)'),
    ('Chillies (Green)'),
    ('China Clay'),
    ('Chlorate of Soda'),
    ('Chrome Alum'),
    ('Chrome Colour'),
    ('Chrome Concentrates'),
    ('Chrome Mortar'),
    ('Chrome Ore'),
    ('Chromium-51'),
    ('Chuni'),
    ('Cinematograph Films Inflammable'),
    ('Citric Acid'),
    ('Clay NOC'),
    ('Cleaning & Washing Fluids Acid'),
    ('Cleaning & Washing Fluids Alkaline'),
    ('Cleaning & Washing Fluids Inflammable'),
    ('Clinker'),
    ('Clove'),
    ('Coal'),
    ('Coal Briquettes'),
    ('Coal Char'),
    ('Coal Dust'),
    ('Coal Dust (<100 micron)'),
    ('Coal Fines'),
    ('Coal Gas Compressed'),
    ('Coal Mill Reject'),
    ('Coal Shale'),
    ('Coal Tar'),
    ('Coal Tar Pitch'),
    ('Coal Tar Pitch (Solid)'),
    ('Coal Tar Residue'),
    ('Coconut'),
    ('Cocopeat'),
    ('Coffee'),
    ('Coke'),
    ('Coke Briquettes'),
    ('Coke Hard'),
    ('Coke Soft'),
    ('Coking Coal'),
    ('Coking Coal (Imported)'),
    ('Coking Coal Washed'),
    ('Cold Drinks / Beverages'),
    ('Cold Rolled Coils'),
    ('Cold Rolled Sheets'),
    ('Coloured Cement'),
    ('Coloured Matches'),
    ('Compressed Air'),
    ('Compressed Gases'),
    ('Container Cargo'),
    ('Containerized Cargo'),
    ('Containers (Empty)'),
    ('Copper Cathode'),
    ('Copper Concentrate'),
    ('Copper Ingot'),
    ('Copper Scrap'),
    ('Copper Slag'),
    ('Copper Wire'),
    ('Copra'),
    ('Cordtex'),
    ('Coriander'),
    ('Coriander Seeds'),
    ('Cosmetics'),
    ('Cotton'),
    ('Cotton Seed'),
    ('Cotton Yarn'),
    ('Cottonseed Oil'),
    ('Courier / Parcel'),
    ('CR Coils (Cold Rolled)'),
    ('Cranes'),
    ('Cranes and Crane Parts'),
    ('CRGO Coils'),
    ('Crude Degummed Soya'),
    ('Crude Oil'),
    ('Crude Palmolein'),
    ('Crude Rubber'),
    ('Crystal Sugar'),
    ('Cumin / Jeera'),
    ('Cumin Seeds'),
    ('Cups and Plates (Metal)'),
    ('DAP (Di-Ammonium Phosphate)'),
    ('DAP (Fertilizer)'),
    ('Dates'),
    ('Defense Equipment'),
    ('Detergent'),
    ('Diapers / Sanitary Pads'),
    ('Diesel (High Speed Diesel / HSD)'),
    ('Diesel Oil'),
    ('Diesel Oil Blended with Biodiesel'),
    ('Diethyl Sulphate'),
    ('Diethylamine'),
    ('Diethylether'),
    ('Dinitro Toluene'),
    ('Distress Signal Rockets'),
    ('DOC (De-Oiled Cake)'),
    ('Dolochar'),
    ('Dolomite'),
    ('Dolomite Chips'),
    ('Dolomite Lumps'),
    ('Dolomite Powder'),
    ('Dozers'),
    ('Drum (Empty)'),
    ('Dry Batteries'),
    ('Dry Chilly'),
    ('Dry Fruits'),
    ('Dry Ginger'),
    ('E-waste'),
    ('Edible Oil'),
    ('Electric Appliances NOC'),
    ('Electric Bulbs'),
    ('Electric Cells'),
    ('Electric Detonators'),
    ('Electric Fans'),
    ('Electric Fuses'),
    ('Electric Lighters'),
    ('Electric Motors'),
    ('Electric Pumps'),
    ('Electric Wires'),
    ('Electrical Goods'),
    ('Electrical Panels'),
    ('Electronic Instruments NOC'),
    ('Electronic Items'),
    ('Empty Barrels'),
    ('Empty Bottles'),
    ('Empty Containers'),
    ('Empty Drums'),
    ('Enamel Nitro-Cellulose'),
    ('Enamels and Paints'),
    ('Engine Oil'),
    ('Engineering Goods'),
    ('Engines'),
    ('Equipment'),
    ('Ethanol'),
    ('Ethyl Acetate'),
    ('Ethyl Butyrate'),
    ('Exhausted / Used Oil'),
    ('Fabric'),
    ('Fabrics'),
    ('Feldspar'),
    ('Ferro Alloys'),
    ('Ferro Chrome'),
    ('Ferro Manganese'),
    ('Ferro Manganese Slag'),
    ('Fertilizer Bags'),
    ('Fertilizers'),
    ('Fire Bricks'),
    ('Fire Wood'),
    ('Fireworks'),
    ('Fish Feed'),
    ('Flatbed Load'),
    ('Fly Ash'),
    ('FMCG Products'),
    ('Food Grains'),
    ('Food Grains and Pulses NOC'),
    ('Footwear'),
    ('Formaldehyde'),
    ('Fresh Fruits'),
    ('Fresh Vegetables'),
    ('Frozen Food'),
    ('Furnace Oil'),
    ('Furniture'),
    ('Fuse Wire'),
    ('Fusel Oil'),
    ('Galvanised Coils'),
    ('Galvanised Sheets (Corrugated)'),
    ('Galvanised Sheets (Plain)'),
    ('Galvanized Sheets (GI)'),
    ('Galvanized Wire'),
    ('Garlic'),
    ('Garments'),
    ('Gas / Compressed Gas'),
    ('Gas Cylinders'),
    ('General Cargo'),
    ('Generator Sets'),
    ('GI Pipes'),
    ('Glass Sheets'),
    ('Glass Stone'),
    ('Glassware'),
    ('Glucose'),
    ('Goat Feed'),
    ('Gram'),
    ('Granite'),
    ('Granite Blocks'),
    ('Granite Blocks Undressed'),
    ('Granite Boulders Undressed'),
    ('Granite Slabs'),
    ('Grapes'),
    ('Gravel'),
    ('Green Chillies'),
    ('Green Pea Seeds'),
    ('Ground Granulated Blast-Furnace Slag'),
    ('Ground Nut Oil Cake'),
    ('Ground Silica'),
    ('Groundnut'),
    ('Groundnut Oil'),
    ('Groundnuts'),
    ('Guar Gum'),
    ('Guar Seed'),
    ('Gunnies (Gunny Bags)'),
    ('Gur (Jaggery)'),
    ('Gypsum'),
    ('Gypsum in Lumps'),
    ('Gypsum in Powder'),
    ('Gypsum / Marine Gypsum'),
    ('H.D.P.E. High Density Polythene Film Grade'),
    ('Hardware'),
    ('Hazardous Cargo'),
    ('HDPE Bags'),
    ('HDPE Granules'),
    ('Heavy Diesel Oil'),
    ('Heavy Diesel Oil (Non-dangerous)'),
    ('Heavy Machinery'),
    ('Heavy Rolls Spoils'),
    ('Hexane'),
    ('Hexene-1'),
    ('Hides & Skins'),
    ('High Flash Low Sulphur Oil'),
    ('High Speed Diesel'),
    ('High Speed Diesel (Blended with Biodiesel)'),
    ('Home Appliances'),
    ('Household Goods'),
    ('HR Coils (Hot Rolled)'),
    ('Hydrated Lime'),
    ('Hydraulic Brake Fluid'),
    ('Hydrochloric Acid'),
    ('Hydrogenated Oils'),
    ('Ice Cream'),
    ('Industrial Chemicals'),
    ('Industrial Equipment'),
    ('Industrial Salts'),
    ('Industrial Solvents'),
    ('Ingot'),
    ('Intermodal Cargo'),
    ('Iron and Steel Material Used Old Defective for Rerolling/Melting'),
    ('Iron and Steel Pipe Cuttings'),
    ('Iron and Steel Slag'),
    ('Iron and Steel Slag (Granulated)'),
    ('Iron Ore'),
    ('Iron Ore Fines'),
    ('Iron Ore for Export'),
    ('Iron Ore Lump'),
    ('Iron Ore Natural Pallet'),
    ('Iron Ore Pellets'),
    ('Iron Ore Powder'),
    ('Iron Ore Rejects'),
    ('Iron Pig (Pig Iron)'),
    ('Iron Pyrites'),
    ('Iron Scrap'),
    ('Iron / Steel Slab'),
    ('Isabgol (Psyllium Husk)'),
    ('Ispat'),
    ('Jaggery'),
    ('Jaggery Powder'),
    ('Jeera'),
    ('Jowar'),
    ('Jute'),
    ('Jute Bags'),
    ('Jute Caddies'),
    ('Kadappa Stone'),
    ('Kapas'),
    ('Kerosene Oil'),
    ('Kinnow'),
    ('Kota Stone'),
    ('Kraft Paper'),
    ('LAB (Linear Alkyl Benzene)'),
    ('Lattice / Transmission Tower Parts'),
    ('Lead'),
    ('Lead Concentrate'),
    ('Leather'),
    ('Leather Cloth'),
    ('Leather Refuse'),
    ('Lemon'),
    ('Lignite'),
    ('Lime Stone'),
    ('Lime Stone Chips'),
    ('Lime Stone Powder / Lumps'),
    ('Limestone'),
    ('Limestone Chips'),
    ('Limestone Powder'),
    ('Liquefied Butane'),
    ('Liquefied Ethane'),
    ('Liquefied Isobutylene'),
    ('Liquefied Petroleum Gas (LPG)'),
    ('Liquid Chlorine'),
    ('Liquid Glucose'),
    ('Liquid Nitrogen'),
    ('Liquid Oxygen'),
    ('Lithium-ion Batteries'),
    ('LNG'),
    ('Locomotives Unassembled Component Parts'),
    ('Loose Cargo'),
    ('LPG'),
    ('Lubricants'),
    ('Lubricating Oils NOC'),
    ('Machine Parts'),
    ('Machinery'),
    ('Machinery Parts'),
    ('Magnesium Alloy Powder'),
    ('Maida'),
    ('Maize'),
    ('Makhana (Fox Nuts)'),
    ('Mangoes'),
    ('Marble Blocks'),
    ('Marble Chips'),
    ('Marble Dressed'),
    ('Marble Powder (All Types)'),
    ('Marble Slabs'),
    ('Marble Undressed'),
    ('Marine Gypsum'),
    ('Masoor Dal'),
    ('Matchbox'),
    ('Meat / Seafood'),
    ('Medical Equipment'),
    ('Medicines / Pharma'),
    ('Melamine'),
    ('Metal Scrap'),
    ('Methane Gas'),
    ('Methanol'),
    ('Methyl Ethyl Ketone'),
    ('Milk Powder'),
    ('Mill Scale Iron or Steel'),
    ('Mill Stone'),
    ('Mineral Gypsum'),
    ('Mineral Turpentine Oil (MTO)'),
    ('Minerals'),
    ('Molasses'),
    ('Molasses Sugar Mill'),
    ('Monazite'),
    ('Monocalcium Phosphate'),
    ('Moong'),
    ('Moong Dal'),
    ('Motor Spirit Blended with Ethanol'),
    ('Motor Spirit (Petrol)'),
    ('Motors'),
    ('MS Angles'),
    ('MS Beams'),
    ('MS Billets'),
    ('MS Billets / Blooms'),
    ('MS Blooms'),
    ('MS Channels'),
    ('MS Flats'),
    ('MS Pipes'),
    ('MS Plates'),
    ('MS Rounds'),
    ('MS Scrap'),
    ('MS Sheets'),
    ('Mustard Oil'),
    ('Mustard Seed'),
    ('Mustard Seeds'),
    ('Namkeen / Snacks'),
    ('Naphtha'),
    ('Naphtha (Barauni)'),
    ('Naphtha (Koyali)'),
    ('Neem Coated Urea'),
    ('Neem Seed'),
    ('Net / Fishing Net Roll'),
    ('Newspaper / Newsprint'),
    ('Newsprint'),
    ('Nickel Scrap'),
    ('Nitric Acid'),
    ('Non-calibrated Lump Iron Ore'),
    ('Non-coking Coal'),
    ('Non-coking Coal Washed'),
    ('NPK Fertilizer'),
    ('Nuts and Bolts'),
    ('Nuts & Bolts'),
    ('Oats'),
    ('ODC Cargo'),
    ('Oil Cake'),
    ('Onion'),
    ('Oranges'),
    ('Organic Manures'),
    ('Over Dimensional Cargo'),
    ('Oxygen Cylinders'),
    ('Packaged Drinking Water'),
    ('Packaging Material'),
    ('Paddy'),
    ('Paddy Parched'),
    ('Paints and Polishes'),
    ('Paints & Varnish'),
    ('Palletized Cargo'),
    ('Pallets'),
    ('Palm Oil'),
    ('Paper'),
    ('Paper Rolls'),
    ('Paraffin Oil'),
    ('Parcel'),
    ('Parcel Cargo'),
    ('Passenger Vehicles'),
    ('Pasta / Noodles'),
    ('Paver Blocks'),
    ('Peas'),
    ('Pebbles'),
    ('Pesticides'),
    ('Pet Coke'),
    ('Pet Coke Cinder'),
    ('Pet Food'),
    ('Petrol (Motor Spirit)'),
    ('Petroleum Ether'),
    ('Petroleum & Hydrocarbon Oils'),
    ('Petroleum Jelly'),
    ('Petroleum Products'),
    ('Pharma'),
    ('Phenol Crystals'),
    ('Phenol Extract'),
    ('Pig Iron'),
    ('Pineapple'),
    ('Pipes'),
    ('Plastic Granules / Dana'),
    ('Plastic Products'),
    ('Plywood'),
    ('Plywood in Boards / Panels'),
    ('Polyhalite'),
    ('Polymers'),
    ('Polymers (LDPE/HDPE)'),
    ('Polypropylene'),
    ('Pomegranate'),
    ('Post Sleepers'),
    ('Potassium Magnesium Sulphate'),
    ('Potassium Sulphate'),
    ('Potato'),
    ('Poultry Feed'),
    ('Power Cable Drums'),
    ('Pressure Vessels'),
    ('Prestressed Cement Concrete'),
    ('Project Cargo'),
    ('Propane'),
    ('PTA (Purified Terephthalic Acid)'),
    ('Putty / Wall Putty'),
    ('PVC Compound'),
    ('PVC Pipes'),
    ('PVC Powder'),
    ('PVC Resin'),
    ('Quartz'),
    ('Quartz / Quartzite Chips / Stones / Gravel / Powder'),
    ('Quartzite'),
    ('Ragi (Finger Millet)'),
    ('Rails P Way Material NOC'),
    ('Railway Rails'),
    ('Railway Wagons Unassembled Component Parts'),
    ('Rajma'),
    ('Raw Petroleum Coke'),
    ('RDF (Refuse Derived Fuel)'),
    ('Readymade Garments'),
    ('Rebar'),
    ('Reclaimed Rubber'),
    ('Reefer Cargo'),
    ('Reefer Containers'),
    ('Refined and Non-refined Edible Oils'),
    ('Refined Oil'),
    ('Reformat'),
    ('Refrigerated Cargo'),
    ('Refrigerator Burning Oil'),
    ('Residual Fuel Oil'),
    ('Resin'),
    ('RFO'),
    ('Rice'),
    ('Rice Bran'),
    ('Rice Broken'),
    ('Rice Common'),
    ('Rice Common Boiled'),
    ('Rice Parmal Broken'),
    ('Rice Raw'),
    ('River Sand'),
    ('Road Surface Dressing of Creosote Pet Residue'),
    ('Rock Phosphate'),
    ('Rolling Stock Parts'),
    ('Roofing Sheets'),
    ('Rubber'),
    ('Rubber Crude'),
    ('Rubber Scrap'),
    ('Rubber Tubes'),
    ('Rubber Tyres'),
    ('RUF Pitch'),
    ('Salt'),
    ('Sand (River)'),
    ('Sand (Silica)'),
    ('Sandal Wood'),
    ('Sandstone'),
    ('Sanitary Pads'),
    ('Sanitary Wares'),
    ('Sanitaryware'),
    ('Sawdust'),
    ('Scaffolding Material'),
    ('Scrap (General)'),
    ('Secondary Nutrient / Soil Conditioner (CMS)'),
    ('Seeds'),
    ('Sesame / Til'),
    ('Sewing Machines'),
    ('Silica Sand'),
    ('Silico Chrome'),
    ('Silico Manganese'),
    ('Silicon'),
    ('Silicon Manganese'),
    ('Sinter'),
    ('Slag'),
    ('Sleeper (Cast Iron)'),
    ('Sleepers (Other than Cast Iron)'),
    ('Small Cardamom'),
    ('Snacks / Edible Snacks'),
    ('Soap'),
    ('Soapstone'),
    ('Soda Ash'),
    ('Soda Ash Dense'),
    ('Soda Ash Light'),
    ('Soda Ash / Sodium Carbonate'),
    ('Soda Bicarbonate'),
    ('Sodium Sulphide'),
    ('Solar Panels'),
    ('Solvents'),
    ('Soya Bean'),
    ('Soya Bean Oil'),
    ('Soya DOC'),
    ('Soya Oil'),
    ('Soya Protein Textured'),
    ('Soyabean Extractions / Tosted Meals / Flakes'),
    ('SoyaBeans Seeds'),
    ('Soybean Oil'),
    ('Spices'),
    ('Sponge Iron'),
    ('Sponge Iron (Fines)'),
    ('Sponge Iron (Lumps)'),
    ('Sports Goods'),
    ('Springs'),
    ('Square Bars'),
    ('Squares (Cast Iron)'),
    ('Squares (Other Than Cast Iron)'),
    ('Squash / Fruit Juice Concentrate'),
    ('Starch'),
    ('Stationery'),
    ('Steel'),
    ('Steel Bars'),
    ('Steel Billets'),
    ('Steel Blooms'),
    ('Steel Coils'),
    ('Steel Pipe Cuttings'),
    ('Steel Pipes'),
    ('Steel Sheet Cuttings'),
    ('Steel Sheets'),
    ('Steel Sheets Pilings'),
    ('Steel Slab'),
    ('Steel Slabs'),
    ('Steel / Stainless Steel Scrap'),
    ('Steel / Stainless Steel Ware'),
    ('Steel Strips'),
    ('Steel Structure'),
    ('Steel Wire Rod'),
    ('Steel Wire Rod Coils'),
    ('Steels'),
    ('Stone'),
    ('Stone Cut'),
    ('Stone Dust'),
    ('Stone Engraved'),
    ('Stone Pillars'),
    ('Stone Ware'),
    ('Straw Reaper & Accessories'),
    ('Sugar'),
    ('Suji'),
    ('Sulphate of Ammonia'),
    ('Sulphate of Soda'),
    ('Sulphate of Zinc'),
    ('Sulphur'),
    ('Sulphur Coated Urea'),
    ('Sulphuric Acid'),
    ('Sunflower Oil'),
    ('Super Fine Cement'),
    ('Super Masonry Cement'),
    ('Super Phosphate'),
    ('Sweet Potato'),
    ('Tallow'),
    ('Tamarind'),
    ('Tamarind Fruit'),
    ('Tamarind Seed'),
    ('Tang'),
    ('Tanker Cargo'),
    ('Tankers (Empty)'),
    ('Tanks / Vessels'),
    ('Tarcoal Drum'),
    ('Tarpaulin'),
    ('Tea'),
    ('Teak Wood'),
    ('Television Sets'),
    ('Temperature Controlled Cargo'),
    ('Tents'),
    ('Textiles'),
    ('Thermo Mechanical Treated (TMT) Bars'),
    ('Tiles'),
    ('Timber'),
    ('Timber Waste'),
    ('Tin Ingot'),
    ('TMT Bars / Rebars'),
    ('Tobacco'),
    ('Toluene'),
    ('Tomato'),
    ('Tower Material'),
    ('Tractors'),
    ('Transformers'),
    ('Transmission Tower Parts'),
    ('Transshipment Cargo'),
    ('Truck Mixers'),
    ('Trucks'),
    ('Tubes / Pipes'),
    ('Tuffen Glass'),
    ('Tur Dal'),
    ('Tur Dal (Pigeon Pea)'),
    ('Turmeric'),
    ('Two-Wheelers'),
    ('Tyres (Auto/Truck)'),
    ('Tyres (OTR / Heavy)'),
    ('U Bend'),
    ('UAP (Urea Ammonium Phosphate 20.20.0)'),
    ('Urad (Black Gram)'),
    ('Urad Dal'),
    ('Urea'),
    ('Urea Ammonium Phosphate 20.20.0'),
    ('Urvara'),
    ('Vaccines'),
    ('Vanaspati Ghee'),
    ('Varnish'),
    ('Vegetable Oil Pitches'),
    ('Vegetable Seeds'),
    ('Vegetables'),
    ('Vehicles (Railway Unassembled Parts)'),
    ('Veneer'),
    ('Wagons Railway Unassembled Component Parts'),
    ('Walnut'),
    ('Warehouse Dispatch'),
    ('Washed Coal'),
    ('Waste Paper'),
    ('Water'),
    ('Water for Industrial Use'),
    ('Water Soluble Fertilizer'),
    ('Watermelon'),
    ('Wax'),
    ('Weld Mesh'),
    ('Wheat'),
    ('Wheat Bran (Chokar)'),
    ('Wheat (PFG)'),
    ('Wheat (SFG)'),
    ('White Cement'),
    ('White Clay (Lumps / Powder)'),
    ('White Peas'),
    ('Wire'),
    ('Wire Rod Coils'),
    ('Wire Rods'),
    ('Wires'),
    ('Wollastonite'),
    ('Wood'),
    ('Wood Pieces'),
    ('Wooden Boxes'),
    ('Wool'),
    ('Work Books'),
    ('Xylene'),
    ('Yarn'),
    ('Yellow Peas'),
    ('Zinc'),
    ('Zinc Concentrate'),
    ('Zinc Ingot'),
    ('Zinc Ores')
),
dedup AS (
  SELECT DISTINCT ON (LOWER(TRIM(name_en))) TRIM(name_en) AS name_en
  FROM raw
  WHERE TRIM(name_en) <> ''
  ORDER BY LOWER(TRIM(name_en)), TRIM(name_en)
),
coded AS (
  SELECT
    name_en,
    NULLIF(REGEXP_REPLACE(LOWER(name_en), '[^a-z0-9]+', '_', 'g'), '') AS base_code
  FROM dedup
),
ranked AS (
  SELECT
    name_en,
    COALESCE(REGEXP_REPLACE(base_code, '^_+|_+$', '', 'g'), 'material') AS normalized_code,
    ROW_NUMBER() OVER (
      PARTITION BY COALESCE(REGEXP_REPLACE(base_code, '^_+|_+$', '', 'g'), 'material')
      ORDER BY name_en
    ) AS code_rank
  FROM coded
),
final_seed AS (
  SELECT
    CASE
      WHEN code_rank = 1 THEN normalized_code
      ELSE normalized_code || '_' || code_rank::TEXT
    END AS code,
    name_en
  FROM ranked
)
INSERT INTO public.materials (
  code,
  name_en,
  group_code,
  keywords,
  popularity_score,
  is_active
)
SELECT
  code,
  name_en,
  'others'::TEXT AS group_code,
  ARRAY[]::TEXT[] AS keywords,
  10 AS popularity_score,
  TRUE AS is_active
FROM final_seed
ON CONFLICT (code) DO UPDATE
SET
  name_en = EXCLUDED.name_en,
  group_code = EXCLUDED.group_code,
  keywords = EXCLUDED.keywords,
  popularity_score = EXCLUDED.popularity_score,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

COMMIT;
